"""Add profile picture to User model

Revision ID: 189ce51d9bac
Revises: 4b8d7ff08282
Create Date: 2024-10-18 14:02:47.184093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '189ce51d9bac'
down_revision = '4b8d7ff08282'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_picture')

    # ### end Alembic commands ###
