"""use templates for weekly workouts

Revision ID: 9879d89736f6
Revises: cf00c77fdc87
Create Date: 2024-10-22 16:33:31.331455

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.exc import ProgrammingError


# revision identifiers, used by Alembic.
revision = '9879d89736f6'
down_revision = 'cf00c77fdc87'
branch_labels = None
depends_on = None


def upgrade():
    try:
        with op.batch_alter_table('weekly_workout', schema=None) as batch_op:
            batch_op.add_column(sa.Column('week_start_date', sa.Date(), nullable=True))
        
        # Update existing rows with a default value
        op.execute("UPDATE weekly_workout SET week_start_date = CURRENT_DATE WHERE week_start_date IS NULL")
        
        # Now make the column not nullable
        with op.batch_alter_table('weekly_workout', schema=None) as batch_op:
            batch_op.alter_column('week_start_date', nullable=False)
    except ProgrammingError as e:
        print(f"An error occurred: {e}")
        print("The column might already exist or there might be existing data. Please check the database state.")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_workout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monday_template_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tuesday_template_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('wednesday_template_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('thursday_template_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('friday_template_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('saturday_template_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sunday_template_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'workout_template', ['tuesday_template_id'], ['id'])
        batch_op.create_foreign_key(None, 'workout_template', ['monday_template_id'], ['id'])
        batch_op.create_foreign_key(None, 'workout_template', ['wednesday_template_id'], ['id'])
        batch_op.create_foreign_key(None, 'workout_template', ['thursday_template_id'], ['id'])
        batch_op.create_foreign_key(None, 'workout_template', ['friday_template_id'], ['id'])
        batch_op.create_foreign_key(None, 'workout_template', ['saturday_template_id'], ['id'])
        batch_op.create_foreign_key(None, 'workout_template', ['sunday_template_id'], ['id'])
        batch_op.drop_column('day')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_workout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('day', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('sunday_template_id')
        batch_op.drop_column('saturday_template_id')
        batch_op.drop_column('friday_template_id')
        batch_op.drop_column('thursday_template_id')
        batch_op.drop_column('wednesday_template_id')
        batch_op.drop_column('tuesday_template_id')
        batch_op.drop_column('monday_template_id')
        batch_op.drop_column('week_start_date')

    # ### end Alembic commands ###
